import { type Mail } from '@/components/DashBoard/types'

export const mailData: Mail[] = [
  {
    id: 'm5gr84i9',
    email: 'ken99@yahoo.com',
    amount: 10,
    message: 'Hello, I am Ken from Toronto. Your package is delivered.',
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: '3u1reuv4',
    email: 'Abe45@gmail.com',
    message: 'Hello, I am Abe from Toronto. Your package is picked up.',
    amount: 20,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'In Transit',
    retrunDate: '2021-10-20',
  },
  {
    id: 'derv1ws0',
    email: 'Monserrat44@gmail.com',
    message:
      'Hello, I am Monserrat from Toronto. Your package is picked up. But something is wroing.',
    amount: 30,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Error',
    retrunDate: '2021-10-20',
  },
  {
    id: '5kma53ae',
    email: 'Silas22@gmail.com',
    message:
      'Hello, I am Silas from Toronto. Your order is pending. Waiting for you to confirm.',
    amount: 30,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Pending',
    retrunDate: '2021-10-20',
  },
  {
    id: 'bhqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'ahqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'chqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'dhqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'ehqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'fhqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'jhqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'hhqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'm5gr84i9',
    email: 'ken99@yahoo.com',
    amount: 10,
    message: 'Hello, I am Ken from Toronto. Your package is delivered.',
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: '3u1reuv4',
    email: 'Abe45@gmail.com',
    message: 'Hello, I am Abe from Toronto. Your package is picked up.',
    amount: 20,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'In Transit',
    retrunDate: '2021-10-20',
  },
  {
    id: 'derv1ws0',
    email: 'Monserrat44@gmail.com',
    message:
      'Hello, I am Monserrat from Toronto. Your package is picked up. But something is wroing.',
    amount: 30,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Error',
    retrunDate: '2021-10-20',
  },
  {
    id: '5kma53ae',
    email: 'Silas22@gmail.com',
    message:
      'Hello, I am Silas from Toronto. Your order is pending. Waiting for you to confirm.',
    amount: 30,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Pending',
    retrunDate: '2021-10-20',
  },
  {
    id: 'bhqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'ahqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'chqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'dhqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'ehqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'fhqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'jhqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'hhqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'm5gr84i9',
    email: 'ken99@yahoo.com',
    amount: 10,
    message: 'Hello, I am Ken from Toronto. Your package is delivered.',
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: '3u1reuv4',
    email: 'Abe45@gmail.com',
    message: 'Hello, I am Abe from Toronto. Your package is picked up.',
    amount: 20,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'In Transit',
    retrunDate: '2021-10-20',
  },
  {
    id: 'derv1ws0',
    email: 'Monserrat44@gmail.com',
    message:
      'Hello, I am Monserrat from Toronto. Your package is picked up. But something is wroing.',
    amount: 30,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Error',
    retrunDate: '2021-10-20',
  },
  {
    id: '5kma53ae',
    email: 'Silas22@gmail.com',
    message:
      'Hello, I am Silas from Toronto. Your order is pending. Waiting for you to confirm.',
    amount: 30,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Pending',
    retrunDate: '2021-10-20',
  },
  {
    id: 'bhqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'ahqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'chqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'dhqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'ehqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'fhqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'jhqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'hhqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'm5gr84i9',
    email: 'ken99@yahoo.com',
    amount: 10,
    message: 'Hello, I am Ken from Toronto. Your package is delivered.',
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: '3u1reuv4',
    email: 'Abe45@gmail.com',
    message: 'Hello, I am Abe from Toronto. Your package is picked up.',
    amount: 20,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'In Transit',
    retrunDate: '2021-10-20',
  },
  {
    id: 'derv1ws0',
    email: 'Monserrat44@gmail.com',
    message:
      'Hello, I am Monserrat from Toronto. Your package is picked up. But something is wroing.',
    amount: 30,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Error',
    retrunDate: '2021-10-20',
  },
  {
    id: '5kma53ae',
    email: 'Silas22@gmail.com',
    message:
      'Hello, I am Silas from Toronto. Your order is pending. Waiting for you to confirm.',
    amount: 30,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Pending',
    retrunDate: '2021-10-20',
  },
  {
    id: 'bhqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'ahqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'chqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'dhqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'ehqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'fhqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'jhqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'hhqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'm5gr84i9',
    email: 'ken99@yahoo.com',
    amount: 10,
    message: 'Hello, I am Ken from Toronto. Your package is delivered.',
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: '3u1reuv4',
    email: 'Abe45@gmail.com',
    message: 'Hello, I am Abe from Toronto. Your package is picked up.',
    amount: 20,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'In Transit',
    retrunDate: '2021-10-20',
  },
  {
    id: 'derv1ws0',
    email: 'Monserrat44@gmail.com',
    message:
      'Hello, I am Monserrat from Toronto. Your package is picked up. But something is wroing.',
    amount: 30,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Error',
    retrunDate: '2021-10-20',
  },
  {
    id: '5kma53ae',
    email: 'Silas22@gmail.com',
    message:
      'Hello, I am Silas from Toronto. Your order is pending. Waiting for you to confirm.',
    amount: 30,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Pending',
    retrunDate: '2021-10-20',
  },
  {
    id: 'bhqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'ahqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'chqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'dhqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'ehqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'fhqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'jhqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'hhqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'm5gr84i9',
    email: 'ken99@yahoo.com',
    amount: 10,
    message: 'Hello, I am Ken from Toronto. Your package is delivered.',
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: '3u1reuv4',
    email: 'Abe45@gmail.com',
    message: 'Hello, I am Abe from Toronto. Your package is picked up.',
    amount: 20,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'In Transit',
    retrunDate: '2021-10-20',
  },
  {
    id: 'derv1ws0',
    email: 'Monserrat44@gmail.com',
    message:
      'Hello, I am Monserrat from Toronto. Your package is picked up. But something is wroing.',
    amount: 30,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Error',
    retrunDate: '2021-10-20',
  },
  {
    id: '5kma53ae',
    email: 'Silas22@gmail.com',
    message:
      'Hello, I am Silas from Toronto. Your order is pending. Waiting for you to confirm.',
    amount: 30,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Pending',
    retrunDate: '2021-10-20',
  },
  {
    id: 'bhqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'ahqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'chqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'dhqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'ehqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'fhqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'jhqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'hhqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'm5gr84i9',
    email: 'ken99@yahoo.com',
    amount: 10,
    message: 'Hello, I am Ken from Toronto. Your package is delivered.',
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: '3u1reuv4',
    email: 'Abe45@gmail.com',
    message: 'Hello, I am Abe from Toronto. Your package is picked up.',
    amount: 20,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'In Transit',
    retrunDate: '2021-10-20',
  },
  {
    id: 'derv1ws0',
    email: 'Monserrat44@gmail.com',
    message:
      'Hello, I am Monserrat from Toronto. Your package is picked up. But something is wroing.',
    amount: 30,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Error',
    retrunDate: '2021-10-20',
  },
  {
    id: '5kma53ae',
    email: 'Silas22@gmail.com',
    message:
      'Hello, I am Silas from Toronto. Your order is pending. Waiting for you to confirm.',
    amount: 30,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Pending',
    retrunDate: '2021-10-20',
  },
  {
    id: 'bhqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'ahqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'chqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'dhqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'ehqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'fhqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'jhqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'hhqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'm5gr84i9',
    email: 'ken99@yahoo.com',
    amount: 10,
    message: 'Hello, I am Ken from Toronto. Your package is delivered.',
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: '3u1reuv4',
    email: 'Abe45@gmail.com',
    message: 'Hello, I am Abe from Toronto. Your package is picked up.',
    amount: 20,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'In Transit',
    retrunDate: '2021-10-20',
  },
  {
    id: 'derv1ws0',
    email: 'Monserrat44@gmail.com',
    message:
      'Hello, I am Monserrat from Toronto. Your package is picked up. But something is wroing.',
    amount: 30,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Error',
    retrunDate: '2021-10-20',
  },
  {
    id: '5kma53ae',
    email: 'Silas22@gmail.com',
    message:
      'Hello, I am Silas from Toronto. Your order is pending. Waiting for you to confirm.',
    amount: 30,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Pending',
    retrunDate: '2021-10-20',
  },
  {
    id: 'bhqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'ahqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'chqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'dhqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'ehqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'fhqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'jhqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'hhqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'm5gr84i9',
    email: 'ken99@yahoo.com',
    amount: 10,
    message: 'Hello, I am Ken from Toronto. Your package is delivered.',
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: '3u1reuv4',
    email: 'Abe45@gmail.com',
    message: 'Hello, I am Abe from Toronto. Your package is picked up.',
    amount: 20,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'In Transit',
    retrunDate: '2021-10-20',
  },
  {
    id: 'derv1ws0',
    email: 'Monserrat44@gmail.com',
    message:
      'Hello, I am Monserrat from Toronto. Your package is picked up. But something is wroing.',
    amount: 30,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Error',
    retrunDate: '2021-10-20',
  },
  {
    id: '5kma53ae',
    email: 'Silas22@gmail.com',
    message:
      'Hello, I am Silas from Toronto. Your order is pending. Waiting for you to confirm.',
    amount: 30,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Pending',
    retrunDate: '2021-10-20',
  },
  {
    id: 'bhqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'ahqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'chqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'dhqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'ehqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'fhqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'jhqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'hhqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'm5gr84i9',
    email: 'ken99@yahoo.com',
    amount: 10,
    message: 'Hello, I am Ken from Toronto. Your package is delivered.',
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: '3u1reuv4',
    email: 'Abe45@gmail.com',
    message: 'Hello, I am Abe from Toronto. Your package is picked up.',
    amount: 20,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'In Transit',
    retrunDate: '2021-10-20',
  },
  {
    id: 'derv1ws0',
    email: 'Monserrat44@gmail.com',
    message:
      'Hello, I am Monserrat from Toronto. Your package is picked up. But something is wroing.',
    amount: 30,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Error',
    retrunDate: '2021-10-20',
  },
  {
    id: '5kma53ae',
    email: 'Silas22@gmail.com',
    message:
      'Hello, I am Silas from Toronto. Your order is pending. Waiting for you to confirm.',
    amount: 30,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Pending',
    retrunDate: '2021-10-20',
  },
  {
    id: 'bhqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'ahqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'chqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'dhqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'ehqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'fhqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'jhqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'hhqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'm5gr84i9',
    email: 'ken99@yahoo.com',
    amount: 10,
    message: 'Hello, I am Ken from Toronto. Your package is delivered.',
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: '3u1reuv4',
    email: 'Abe45@gmail.com',
    message: 'Hello, I am Abe from Toronto. Your package is picked up.',
    amount: 20,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'In Transit',
    retrunDate: '2021-10-20',
  },
  {
    id: 'derv1ws0',
    email: 'Monserrat44@gmail.com',
    message:
      'Hello, I am Monserrat from Toronto. Your package is picked up. But something is wroing.',
    amount: 30,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Error',
    retrunDate: '2021-10-20',
  },
  {
    id: '5kma53ae',
    email: 'Silas22@gmail.com',
    message:
      'Hello, I am Silas from Toronto. Your order is pending. Waiting for you to confirm.',
    amount: 30,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Pending',
    retrunDate: '2021-10-20',
  },
  {
    id: 'bhqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'ahqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'chqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'dhqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'ehqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'fhqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'jhqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
  {
    id: 'hhqecj4p',
    email: 'carmella@hotmail.com',
    message: 'Hello, I am Carmella from Toronto. Your package is delivered.',
    amount: 40,
    pickupAddress: {
      apartmentUnitNumber: '12A',
      streetNumber: 1234,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    deliveryAddress: {
      apartmentUnitNumber: '0',
      streetNumber: 999,
      streetName: 'Main St',
      city: 'Toronto',
      province: 'ON',
      postal: 'M1M1M1',
    },
    shippingStatus: 'Delivered',
    retrunDate: '2021-10-20',
  },
]
